#![doc = include_str!("README.md")]

pub mod board;
pub mod cpu;
pub mod datetime;
pub mod disk;
pub mod gpu;
pub mod initsystem;
pub mod kernel;
pub mod locale;
pub mod memory;
pub mod os;
pub mod publicip;
pub mod shell;
pub mod terminal;
pub mod theme;
pub mod title;
pub mod uptime;
pub mod wallpaper;
pub mod weather;
